### ISSUE TITLE
can I add a custom chain?

### ISSUE THREAD

**Issue by randomshinichi** [chainapsis/keplr-extension#104]
I would like to connect to an RPC endpoint of my own.

**Comment by dogemos** [comment]
Hi @randomshinichi,

Right now we don't have a in-extension interface to add a new chain to Keplr, but you can create a basic mock website and refer to the code [in our documentation](https://docs.keplr.app/api/suggest-chain.html) for the front-end to suggest a chain to Keplr wallet.

**Comment by Rodri-dev** [comment]
An in-extension interface for this would be amazing
