### ISSUE TITLE
Can't undelegate staking when there is no crypto in wallet.

### ISSUE THREAD

**Issue by DatN132** [chainapsis/keplr-extension#108]
It would be nice if it is configured such that the gas fee is taken from the staked amount rather than from the wallet in case people delegate everything without leaving anything back for undelegating. Also, you cannot claim staking rewards without first have free (non-staked) crypto in the wallet

**Comment by dogemos** [comment]
Hi @DatN132,

Unfortunately, this isn't something we can change on the client-side. Staked tokens being completely illiquid is something that's enforced at the on-chain level.
