### ISSUE TITLE
Uncatchable CSR error on firefox

### ISSUE THREAD

**Issue by Thunnini** [chainapsis/keplr-extension#11]
It seems that firefox blocks the eval() function default due to security reasons. 
Thus, the code bundled by the webpack and web3js
```javascript
try {
	// This works if eval is allowed (see CSP)
	g = g || new Function("return this")();
} catch (e) {
	// This works if the window reference is available
	if (typeof window === "object") g = window;
}
```
throws the CSR error. However, it seems that this try-catch statement can't catch the error from `new Function("return this")()` on firefox.
To solve this problem, we can permit the eval() function. But, this way has potential security risks. So, it is needed to find the desired way without permitting eval() function.

**Comment by Alko89** [comment]
I know this is not entirely related to the issue, but I didn't think it was worth opening one just for that (if you want I still can).
How can I install this plugin in Firefox?

**Comment by Thunnini** [comment]
@Alko89 We have stopped publishing the extension on the official firefox addon page due to some issues + lack of resources to address both Chrome and Firefox. 

However, you can build + install this extension manually by running `npm run build` and it will make the output to `prod` folder. And, you can follow this instruction to install it. https://developer.mozilla.org/ko/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension
