### ISSUE TITLE
Invalid address when sending Tokens from osmosis

### ISSUE THREAD

**Issue by musenzi** [chainapsis/keplr-extension#113]
When using the Osmosis chain in keplr the address shows as invalid when trying to send tokens like ATOM to another address
My guess is that the the form checker is checking for a valid OSMO address instead of checking the validity of the token address.

Reproduce:
Swap some tokens like ATOM with the osmosis app

1. Open keplr and change chain to Osmosis
2. Go to tokens and click on the one you want to send
3. Enter address of recipient 

You'll get an invalid address notification beneath the textbox

**Comment by dogemos** [comment]
Please use the [assets page](https://app.osmosis.zone/assets) for deposits/withdrawals
