### ISSUE TITLE
Bonding in Osmosis/Atom pool 1

### ISSUE THREAD

**Issue by Mickeyt64** [chainapsis/keplr-extension#116]
Transaction has repeatedly failed even though there are sufficient OSMO to cover multiple txt fees
" out of gas in location: WritePerByte:

**Comment by CryptoMarco** [comment]
I have the same issue :(
to make it even worse I have complete all airdrop missions a part of holding ATOM in FEB and all off them are still shown as ineligible. Anyone know how to sort it out?

**Comment by Mickeyt64** [comment]
I have worked it out ( embarrassingly )
Before you hit the "approve" button you will see "set gas". click on set gas & at least double it.
Can set as high as you like & the network will only use what is required.

**Comment by CryptoMarco** [comment]
Thank you for your response.I have done as you said and it worked.Thank you!Do you know how to reset the Osmosis, as it still show my progress on airdrop on 0% despite me completing 4/5 missions.Kind RegardsMarekSent from my Galaxy
-------- Original message --------From: Michael Trethowan ***@***.***> Date: 02/07/2021  01:04  (GMT+00:00) To: chainapsis/keplr-extension ***@***.***> Cc: CryptoMarco ***@***.***>, Comment ***@***.***> Subject: Re: [chainapsis/keplr-extension] Bonding in Osmosis/Atom pool 1 (#116) 
I have worked it out ( embarrassingly )
Before you hit the "approve" button you will see "set gas". click on set gas & at least double it.
Can set as high as you like & the network will only use what is required.

**Comment by Mickeyt64** [comment]
would not worry about that to much as long as you received OSMO for each
mission.
If you did not than maybe redo missions to receive the staged airdrops
Cheers Michael
