### ISSUE TITLE
ATOM not showing in my OSMOSIS Keplr wallet

### ISSUE THREAD

**Issue by Carolinamoon** [chainapsis/keplr-extension#118]
When I search on Mintscan, my wallet address shows the test amount that I sent was successful.

Public address cosmos1ry29qr4524ph7ky6hm5c6n5uq02wxqv5lv6k25

Issue is seeing a zero balance in OSMOSIS, linkage to Keplr wallet is not reflecting available ATOMS

**Comment by dogemos** [comment]
Hey @Carolinamoon, was this resolved?
