### ISSUE TITLE
[new feature] import 12-words mnemonic account

### ISSUE THREAD

**Issue by liangping** [chainapsis/keplr-extension#124]
I have an account in hardware wallet with 12 mnemonic.  There's no way to import to Keplr.

**Comment by dogemos** [comment]
Hi @liangping,

Keplr extension follows the BIP39 standard and supports 12/15/18/21/24 word mnemonics. What is the error you are getting?

**Comment by liangping** [comment]
@dogemos I got `Invalid mnemonic`, seems that I got a wrong mnemonic.
Thank you.
