### ISSUE TITLE
Restored Keplr Wallet Using Seed Phrase Now Balance is Zero

### ISSUE THREAD

**Issue by NanoRebel** [chainapsis/keplr-extension#138]
I had to restore my Keplr Wallet using my seed phrase because for some odd reason the wallet password stopped working. I wrote it down and didn't change it so I have no idea why it stopped working. When deleted then reinstalled the Keplr Chrome extension and restored my wallet with the seed phrase my Sentinel balance was zero and there's a new address associated with the Sentinel wallet. If I use the COSMOS block explorer and check my original wallet address all my coins are there but I can't access them via Keplr. I also tried importing the seed phrase into the Cosmostation mobile wallet, with the same result...balance is zero. Any suggestions would be appreciated! Thanks.

**Comment by giansalex** [comment]
It seems that seed phrase is different.

**Comment by NanoRebel** [comment]
It's not different, I took a screenshot when I set it up so I know it's the proper seed phrase. Now, the password I created to  recover the wallet isn't working. It seems there's some kind of glitch going on with either the Keplr wallet or Chrome. I lost access to a substantial amount of coins.
