### ISSUE TITLE
Add Desmos to Keplr

### ISSUE THREAD

**Issue by wimel** [chainapsis/keplr-extension#147]
Please add support to [Desmos](https://github.com/desmos-labs) blockchain to help users to manage their founds and use Osmosis in a simpler way. Thanks!

**Comment by delivan** [comment]
Hey @wimel ,

Unfortunately, we have an internal decision-making process in regards to native chain support for Keplr wallets. Native chain support requires evaluations on monitoring, operational overhead, infrastructure requirements, business strategy decisions, resource overhead which need to be discussed and met.

In the meantime, please feel free to use the permissionless 'suggestChain' feature or reach out if you'd like to discuss native integration to Keplr.

**Comment by kurt2727** [comment]
Hi there, 
I mistakenly deleted the Desmos (beta support) chain from my Keplr wallet - could anyone tell me how to add it back in? 
many thanks!

**Comment by WeiJun0827** [comment]
@kurt2727 According to Desmos' [Twitter post](https://twitter.com/desmosnetwork/status/1463893502505496583), you can add Desmos chain into Keplr wallet by clicking the 'Use Keplr' button in https://go-find.me page.
