### ISSUE TITLE
Unusable with Certik network

### ISSUE THREAD

**Issue by phantomcrypt** [chainapsis/keplr-extension#148]
There seems to be a problem with certik overall. No validators are shown, which makes impossible to delegate/re-delegate.

Claiming rewards gives this error:
```
Fail to withdraw rewards: Account's type is unknown: {"address":"XXX","public_key":{"type":"tendermint/PubKeySecp256k1","value":"XXX"},"account_number":"2117","sequence":"52"}
```

Possibly due to the [network upgrade](https://explorer.certik.foundation/governance/proposals/4?net=shentu-2).

**Comment by dogemos** [comment]
Fixed in https://github.com/chainapsis/keplr-extension/releases/tag/v0.8.15. Release going out today/tomorrow!
