### ISSUE TITLE
mnemonic vs private key

### ISSUE THREAD

**Issue by pan-dusan** [chainapsis/keplr-extension#149]
Hello,
currently it is possible to reveal only private key in extension. However for full control mnemonic is required. Other wallets offer edit mode (send/receive, etc.) only with mnemonic entered. For importing mnemonic is required as well. How can I get mnemonic seed?
Thanks

**Comment by dogemos** [comment]
Hi there,

We offer the 'view private key' option specifically for accounts that were created with the 'Log in with Google' feature. We use Torus for this, and Torus only creates a private key, not a mnemonic for this. For other accounts created with a mnemonic, we reveal the mnemonic phrase by default.

**Comment by Kwaskoff** [comment]
But when I have just exported from gaia private key - how I can import it to keplr?
