### ISSUE TITLE
Please publish android APKs as part of a release

### ISSUE THREAD

**Issue by AFDudley** [chainapsis/keplr-extension#166]
Thanks so much for all the great work, I really appreciate it. Could you please publish all the APKs you send to google as part of the github release? airgapped phones often times don't have access to the Google Play Store.

Thanks again.

**Comment by Thunnini** [comment]
I've been thinking about it, but it seems difficult to guarantee that the apk is uploaded every time. Sorry, I'll close the issue.

**Comment by monomadic** [comment]
This leaves those with a secure os like Graphene or Calyx to basically use (potentially dodgy) playstore proxies. I'm not sure anyone needs a guarantee, but surely it's a matter of extending the CI/CD process?
