### ISSUE TITLE
Unable to convert cosmos address to terra address

### ISSUE THREAD

**Issue by Dirt-Nasty** [chainapsis/keplr-extension#170]
I was hoping you would be able to provide some insight.

I typically take a cosmos public address and decode it and then encode it using the network prefix ex. “osmo” and the decoded response from the cosmos public address.

I’ve tried this with terra but for some reason what I am getting after re-encoding is not match what is shown as the address in Keplr.

Can you give any insight if there is additional data manipulation that should occur before re-encoding it?

**Comment by giansalex** [comment]
Terra has different CoinType: `330`
https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by Dirt-Nasty** [comment]
How does that factor into the encoding of the public wallet address?
