### ISSUE TITLE
feature request: disable balance checking

### ISSUE THREAD

**Issue by clockworkgr** [chainapsis/keplr-extension#181]
It is possible to have a chain that implements certain fee-less messages/transactions.

In those situations it would be nice to have a configuration option (similar to preferNoSetFee / preferNoSetMemo) that disables balance checking altogether.

Thanks

**Comment by RiccardoM** [comment]
@Thunnini Is it possible to work on this? Currently due to the automatic balance checking it's impossible to use the [`fee_payer`](https://docs.cosmos.network/master/modules/feegrant/01_concepts.html#feeaccount-flag) eature when signing something with Keplr

**Comment by Thunnini** [comment]
@RiccardoM It will be in the next version.

**Comment by RiccardoM** [comment]
> @RiccardoM It will be in the next version.

Thanks! Any ETA for that?

**Comment by Thunnini** [comment]
will be within a week

**Comment by Thunnini** [comment]
@clockworkgr @RiccardoM This issue is resolved in the v0.9.9 and that is published

**Comment by RiccardoM** [comment]
> @clockworkgr @RiccardoM This issue is resolved in the v0.9.9 and that is published

Thank you! :pray:

**Comment by MikeSofaer** [comment]
This is awesome, thank you all!
