### ISSUE TITLE
Initial window  cuts off and has no scrollbar

### ISSUE THREAD

**Issue by josephj11** [chainapsis/keplr-extension#189]
When I open some websites which use Cosmos/Keplr, a Keplr window automatically opens. This is as expected, but the window is too small for content and the bottom is cut off with no way to scroll to it to see and fill in the password field.

Maximizing the Keplr window fixes this, but should be unnecessary.

I think reducing screen magnification might also fix this, but messes up the rest of the display.

This doesn't happen all the time and is a bit hard to recreate. I think it may have to do with the first time it gets invoked after a long time. I don't completely log out of my user or reboot very often, so I don't think it's that.

Just giving the window a vertical scrollbar when it's not maximized should fix this.

I am using the Vivaldi browser (chromium based) on kubuntu Linux 18.04 (KDE desktop environment).

![Selection_035](https://user-images.githubusercontent.com/4546046/141646404-8a1e4072-f47a-4611-8a1e-979121b4a0c7.png)

**Comment by Thunnini** [comment]
Was the scaling of the web browser itself set to 100%? Only the Chrome browser is officially supported, but I'll take a look at it when I have time.

**Comment by josephj11** [comment]
Thanks for looking at this.

I usually keep the scaling at 100%, but I'm not sure for this case. I will make a note of it if it happens again.

I imagine that a lot of users will be using Brave, Vivaldi, or another more privacy friendly browser for financial activities and especially for cryptocurrency transactions, so it would be good if they were supported, but I understand that doing so takes additional time and effort.

From the outside (not knowing your code base at all), the fix for this appears to be easy - just adding a vertical scrollbar either unconditionally, or when the need for it is detected.

**Comment by josephj11** [comment]
Just happened again. Both the main window and the Keplr window are at 100% scaling.
![Selection_036](https://user-images.githubusercontent.com/4546046/143793343-1787a580-8f62-4bc5-bd85-c86f4d655974.png)

Thanks for your attention.
