### ISSUE TITLE
Wallet not showing all staked SCRT

### ISSUE THREAD

**Issue by jrkang8** [chainapsis/keplr-extension#192]
![image](https://user-images.githubusercontent.com/94646920/142492818-ae1a80ec-99fe-4b88-b369-18dcef2a0785.png)

I'm only able to manage part of my staked coins. Where are the rest of my staked?

**Comment by Thunnini** [comment]
Can you tell me your account address?

**Comment by jrkang8** [comment]
secret1dk6269dc09a8fvexfgsaqnyk7e2ar53mrk3agw

**Comment by Thunnini** [comment]
I think this issue has been resolved.

**Comment by jrkang8** [comment]
its resolved:
![image](https://user-images.githubusercontent.com/94646920/142676858-15dbb089-82a4-45a0-9b78-b3581acf3bc6.png)


thanks
