### ISSUE TITLE
Android app bug

### ISSUE THREAD

**Issue by michael60634** [chainapsis/keplr-extension#193]
After launching and unlocking the Android app, the balances show briefly, then the startup logo screen is shown. The startup screen does not go away and the app is unable to be used.

Device: Google Pixel 4
Android version: 12
App version: 1.0.9

**Comment by dogemos** [comment]
Haven't been able to reproduce it yet. But will keep a lookout for it.

**Comment by michael60634** [comment]
Thanks for the update. I've seen some users reporting this problem in the Google Play Store reviews.

**Comment by jimrubbers** [comment]
Still having problems with this even after the update. Is there any way I can help to fix this? Logcats or anything?
