### ISSUE TITLE
Terra + Ledger broken. My money is stuck!

### ISSUE THREAD

**Issue by demian85** [chainapsis/keplr-extension#203]
Hey guys,

I'm very confused. It'd be nice if I had known better before transferring money to my Terra address using Keplr and Ledger.
I wanted to wrap UST -> sUST so I transferred money from my main Terra address using Terra Station + Ledger.
Now I have 2 problems:
- I cannot properly sign a transaction on https://wrap.scrt.network/
- I cannot even transfer my UST to my original Terra address. I have 0.1 LUNA and after signing the tx on the Ledger it fails stating I do not have enough for gas fees, which is supposed to be $0.04

Is this a bug and will be fixed soon? I have 2k UST stuck there and I need to move them! Please help!

**Comment by Thunnini** [comment]
terra was added externally through the suggest chain and is not officially supported. So this is not a bug. Contact the secret network team.
