### ISSUE TITLE
"Insufficient available balance for transaction fee" for multisig accounts

### ISSUE THREAD

**Issue by greg-szabo** [chainapsis/keplr-extension#204]
Great extension! I use it regularly.

I am testing Keplr with legacy multisig transactions on the Cosmos Hub. When I try to submit a send transaction from a multisig address, Keplr keeps the "Approve" button grayed out. When I click "override fee", I get `Insufficient available balance for transaction fee` under the choices for fee. (This might or might not be multisig-related, I'm not sure.)

The account definitely has enough free ATOMS, so I'm not sure why Keplr is so adamant.

How to recreate the issue:

Here's a demo website that will trigger Keplr: https://cosmoshub-legacy-multisig.vercel.app/multi/cosmos16k579jk6yt2cwmqx9dz5xvq9fug2tekv6g34pl/transaction/316472223760122449

The website is an Interchain Foundation demo project. Source code is hosted here: https://github.com/samepant/cosmoshub-legacy-multisig

Alternatively, here is the actual transaction JSON:
```
{
  "chain_id": "cosmoshub-4",
  "account_number": "21021",
  "sequence": "62",
  "fee": {
    "gas": "200000",
    "amount": [
      {
        "amount": "6000",
        "denom": "uatom"
      }
    ]
  },
  "msgs": [
    {
      "type": "cosmos-sdk/MsgSend",
      "value": {
        "from_address": "cosmos16k579jk6yt2cwmqx9dz5xvq9fug2tekv6g34pl",
        "to_address": "cosmos1fghgwhgtxtcshj4a9alp7u2qv6n2wffqj4jdl9",
        "amount": [
          {
            "amount": "1000000",
            "denom": "uatom"
          }
        ]
      }
    }
  ],
  "memo": ""
}
```

You can check on the chain that the `from_address` has enough free tokens for the transaction.

Is it possible that Keplr checks the `from_address` and only allows signatures from that address? (Which would make multisig signatures impossible.)

**Comment by Thunnini** [comment]
The reason this happens is that the sender is the current account selected, not from the msgs in the transaction. I will fix it soon.

**Comment by Thunnini** [comment]
@greg-szabo From v0.9.9, the balance is checked by considering the sender of msgs in tx. However, in the case of the fee part, it seems a bit difficult to measure which account will actually pay the fee. So, the fee part was not processed. If the multi-sig accounts have some balance of fee, it will pass. However, in the case of multi-sig, it is recommended to use the `disableBalanceCheck` option to turn off the balance check feature itself.
