### ISSUE TITLE
Ideation for feature to allow user/webpage to add arbitrary blockchains

### ISSUE THREAD

**Issue by Thunnini** [chainapsis/keplr-extension#26]
It is useful to allow a user or webpage to give the option of adding a chain to Keplr. It can increase the usability of Keplr in cases where a user wants to use the Keplr on a testnet or other chains that are not natively supported on Keplr. To implement this feature, we need to some research and decision making.

### Requirement
 - There are necessary information about the chain in order to Keplr to create the account and send assets on Keplr's UI and so on...
 - Below is the list of information required for natively supported chains on Keplr
```typescript
export interface ChainInfo {
  readonly rpc: string;
  readonly rpcConfig?: AxiosRequestConfig;
  readonly rest: string;
  readonly restConfig?: AxiosRequestConfig;
  readonly chainId: string;
  readonly chainName: string;
  /**
   * This indicates the type of coin that can be used for stake.
   * You can get actual currency information from Currencies.
   */
  readonly nativeCurrency: string;
  readonly walletUrl: string;
  readonly walletUrlForStaking?: string;
  readonly bip44: BIP44;
  readonly bech32Config: Bech32Config;

  readonly currencies: string[];
  /**
   * This indicates which coin or token can be used for fee to send transaction.
   * You can get actual currency information from Currencies.
   */
  readonly feeCurrencies: string[];
  /**
   * This is the coin type in slip-044.
   * This is used for fetching address from ENS if this field is set.
   */
  readonly coinType?: number;
}

export interface Currency {
  coinDenom: string;
  coinMinimalDenom: string;
  coinDecimals: number;
  /**
   * This is used to fetch asset's fiat value from coingecko.
   * You can get id from https://api.coingecko.com/api/v3/coins/list.
   */
  coinGeckoId?: string;
}
```
 - And it probably necessary to know the cosmos-sdk version that the chain built on because the logic can be different according to the version `launchpad` or `stargate` in the future. 
 - However, it seems not a good way to require all the information to suggest a chain. Some pieces of information can be known from its RPC and rest API.

### Information that can be omitted 
 - RPC and rest API is required because they are used by the Keplr to broadcast tx or query state.
 - Chain-id can be omitted because it can be known through other methods such as `https://node-cosmoshub-3.keplr.app/rpc/block?height=1`. And, it is important to make the user know the chain id that is suggested on UI. And, possibly it can be checked that the suggested chain id and node's chain id is matched if the chain is suggested with the explicit chain-id. 
 - The bip44 path is not required technically because the account can be created with any bip44 path (in this case, the bip44 path will be the cosmoshub's bip44 path). However, it can cause user confusion if the chain's bip44 path is different from cosmoshub's bip44 path. If the bip44 path is different, the account that is created on Keplr and another account that is created on the other wallet will be different even with the same mnemonic.
 - Bech32 config is required, and it seems that it can't be known from RPC or rest API. Bech32 config is used to show the address to the user and check the validity of the recipient's address when sending assets and so on...
 - Currency is required because Keplr must know the coin/token information of the chain to show the asset amount on account and to send assets to the other account. However, it can be known from the node if this [ADR](https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-024-coin-metadata.md) is implemented even though it can be not supported according to the cosmos-sdk version...
 - CoinType is the number that is decided socially on [Slip-044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md). Currently, it is used to fetch the address from the ENS when sending assets. So, it can be optional.
 - WalletUrl, WalletUrlForStaking is the URL of the wallet. They are only used to link the wallet to the user on Keplr's UI. So, it can be optional. If a suggester wants to user to know the specific wallet's URL, the suggester can suggest the chain with the specific wallet's URL. If not, the user can go to the wallet manually on the browser.

### Unconfirmed discussion
 - It is advisable to minimize required fields.
 - We can submit the ADR that notifies the bech32 and bip44 path information by the rest API on the cosmos-sdk if we have the resources.
 - Some data such as CoinType or CoinGeckoId probably can be updated by the trusted server that we operate because they are natively not sensitive data.

**Comment by ethanfrey** [comment]
Thank you for this write up and I like the general idea. I have a bit of confusion of separation of concerns and what goes in the webpage and what in the extension, which I mentioned here: https://github.com/CosmWasm/cosmjs/pull/403#issuecomment-681864668

When that is cleared up, I can comment a bit more. Here are my first comments:

>   `readonly currencies: string[];`
What about `readonly currencies: Currency[];` (which I think you mean).

> coinDenom: string;
>  coinMinimalDenom: string;
Please add an comment here to clarify, I assume coinDenom = "ATOM" (display token) and coinMinimalDenom = "uatom" (chain token)

>   readonly nativeCurrency: string;
Is this better named `stakingCurrency`? currencies and feeTokens are also native

>  readonly feeCurrencies: string[];
Please document if this is in `coinDenom` or `coinMinimalDenom`

>  readonly walletUrl: string;
>  readonly walletUrlForStaking?: string;
These should link to webapps that support Keplr extension, right?

**Comment by ethanfrey** [comment]
> And it probably necessary to know the cosmos-sdk version that the chain built on because the logic can be different according to the version launchpad or stargate in the future.

Definitely good to have a version field to know what type of chain.

> However, it seems not a good way to require all the information to suggest a chain. Some pieces of information can be known from its RPC and rest API.

It is good to clarify chain-id here, this makes sure we didn't mistype with the rpc url. Also, if some info can be polled from the chain, that would be good, but much cannot currently. Ideally all the currency info is via rpc (maybe in stargate).

Also, the `gasPrice` has no api to determine and must be magically known currently. It would be good to add that here.

**Comment by Thunnini** [comment]
@dogemos I have an idea which is not directly related to this issue. 
We should prepare the chain update because sometimes the chain based on cosmos-sdk will update the chain itself.
And, Secret network will be updated soon. My idea is that after obtaining information through rpc and rest endpoint if there is any changed information, a warning is displayed to the user whether to update the chain information and then updated based on that information. In this direction, we can get information from a node without having a separate trusted server and let the user decide whether to choose to update.

**Comment by Thunnini** [comment]
The initial experimental method that suggests the chain is added. https://github.com/chainapsis/keplr-extension/blob/master/src/content-scripts/inject/common.ts#L17

**Comment by Thunnini** [comment]
The example to use `keplr.experimentalSuggestChain` is added. https://github.com/chainapsis/keplr-example/blob/cw-20/src/main.js#L19

**Comment by dogemos** [comment]
Closing issue as feature has been deployed.
