### ISSUE TITLE
Errors are not shown to user

### ISSUE THREAD

**Issue by faboweb** [chainapsis/keplr-extension#38]
Example state after setting fees

![image](https://user-images.githubusercontent.com/5869273/97719386-0322e580-1a95-11eb-96ac-5bc7fc1da8ae.png)

**Comment by Thunnini** [comment]
Could you explain the situation in more detail?

**Comment by faboweb** [comment]
I am using the experimental network suggest function. I added a network with wrong parameters. When sending a tx this state happened. There is no error visible to the user. Just a blanc screen.

**Comment by Thunnini** [comment]
Yes, this feature is still experimental, so error handling is still somewhat insufficient. After deleting the registered chain, and then set the correct parameters again, I think it will be resolved.

**Comment by faboweb** [comment]
Yep that works. Just wanted to point out, that showing the error would be helpful
