### ISSUE TITLE
delegation to validator no longer in set of block producers

### ISSUE THREAD

**Issue by okwme** [chainapsis/keplr-extension#41]
hello,
i have an old delegation to a validator that is no longer in the validator set. I can see it show up in the pie chart that described my delegations, but it does not show up under the list of validators. This is probably because that validator is offline and/or no longer in the validator set. Would be great if it was still included tho so I could re-delegate : )

**Comment by Thunnini** [comment]
I added the feature that shows the inactive validator to the wallet.keplr.app's dashboard. I think that showing an inactive validator to the all validator page can be confusing. Anyway, you can unbond/redelegate inactive validator in your dashboard.

**Comment by okwme** [comment]
thank you works great!!
