### ISSUE TITLE
balance showing 0 with warning sign

### ISSUE THREAD

**Issue by okwme** [chainapsis/keplr-extension#42]
the chrome extension is showing a balance of 0 but the correct amount of rewards available. When I try to withdraw rewards i get the following error:
```
Error occurs during fetching assets: TypeError: Cannot read property 'length' of undefined
```
The same error shows up when i refresh the extension and inspect the console.

any idea what it could be?

**Comment by Thunnini** [comment]
This issue likely occurs because Keplr can't parse the vesting account. But, in v0.7.1 which now been published, I fixed that Keplr can parse the vesting account without regarding the vesting/vested amount. Let me know that this issue is resolved.

**Comment by okwme** [comment]
just updated to v0.7.1 and there's no longer an error!
My "Available" tokens was inaccurate at first, it might have been the original vested amount. Once I claimed my pending staking reward it was updated to the correct amount though : )

Thank you!!
