### ISSUE TITLE
Only show denoms that has a balance

### ISSUE THREAD

**Issue by mdyring** [chainapsis/keplr-extension#44]
For the e-Money mainnet there are many denoms for stablecoins, but users might not have a balance.

It would be great to remove the denoms from the dropdown that have a zero balance:

![image](https://user-images.githubusercontent.com/18033781/100427077-2fc91d80-3092-11eb-814b-4174b9989397.png)

**Comment by delivan** [comment]
Hi, @mdyring 

We updated to show denoms that has a balance on send page.
It has been published to v0.9.9. Let me know that the issue is resolved.

Thank you
