### ISSUE TITLE
Allow flexibility in WithdrawReward transactions

### ISSUE THREAD

**Issue by AdityaSripal** [chainapsis/keplr-extension#49]
The current extension allows users to withdraw rewards from all validators in a single transaction. However, if the user is delegated to many validators, this may end up being too large of a transaction to send.

The Keplr wallet should allow users to selectively batch withdraw rewards from specific validators rather than only allowing all rewards to be withdrawn.

I currently get an error `JSON: too many tokens` when I try to withdraw my rewards using Keplr because of this issue.

**Comment by dogemos** [comment]
Hi @AdityaSripal, Keplr now batches the claim reward transaction in the order of top 8 pending rewards as of v0.8.4. Thanks for bringing this up, and please let us know if you have any more suggestions/feature requests!

https://github.com/chainapsis/keplr-extension/issues/61#issuecomment-813256125
