### ISSUE TITLE
Firefox Version 8)

### ISSUE THREAD

**Issue by peepopoggers** [chainapsis/keplr-extension#50]
A firefox version would be a great addition, in terms of pushing privacy and security.
Is there an ETA or anything in the works? Thanks!

**Comment by dogemos** [comment]
Hi @peepopoggers, first off, apologies for the delay on the reply.

We've previously shipped Keplr for Firefox, as well as Chrome–but quickly realized that there are some critical issues with the UI rendering as well as the Firefox web store review having issues with certain dependencies. It's something we'd like to tackle in the future, but for now, our resources will be directed towards improving our Chrome extension and mobile wallet.

No ETA, but we are fully supportive of eventually offering Keplr extension to Firefox users.

**Comment by imsys** [comment]
The main thing that keeps me on Firefox is the Tree Style Tab extension, I can't live without that. There are some attempts to make a similar extension in chrome, but none of them work as well as Firefox TST.
Mobile users represent over 50% of the browsing, while Firefox represent only 4% of the browser market, so I understand the way the priority was given.

I see the dedication and how hard you guys are working on keplr by the high frequency of commits.
But if the resources are short, maybe we could ask the the cosmos ecosystem to spare some funds to hire more devs.
Anyway, I will be waiting for it, and happy new year!
