### ISSUE TITLE
keplr allows access approval before unlocking

### ISSUE THREAD

**Issue by okwme** [chainapsis/keplr-extension#51]
just visited cyper.page and before i could unlock keplr i was prompted to approve access. It seemed to work but seems like that shouldn't be possible until keplr is unlocked?

**Comment by Thunnini** [comment]
This may look a bit odd, but to request an unlock you must first receive permissions through the access approval, so what you’ve done so far is correct.

In the meantime, I’ll think if there are ways to improve this.
