### ISSUE TITLE
Popup: "Chain information has changed. Verify that a chain upgrade has taken place"

### ISSUE THREAD

**Issue by 59023g** [chainapsis/keplr-extension#57]
<img width="362" alt="Screen Shot 2021-02-19 at 4 58 41 PM" src="https://user-images.githubusercontent.com/5235538/108571054-eaa13a00-72d4-11eb-9c61-d68bba06ee3b.png">

Hey, This pop-up reappears for every action I try to make with Keplr wallet. Is it possible to store my response so it only asks once?

**Comment by dogemos** [comment]
Closing issue as the bug has been patched in the latest release of Keplr.
