### ISSUE TITLE
Sifchain gas too low. Transactions fail

### ISSUE THREAD

**Issue by 59023g** [chainapsis/keplr-extension#59]
<img width="336" alt="Screen Shot 2021-02-19 at 8 16 08 PM" src="https://user-images.githubusercontent.com/5235538/108580029-4ed0f780-72ef-11eb-8100-8d6bc1c435c1.png">

PR: https://github.com/chainapsis/keplr-extension/pull/58

**Comment by dogemos** [comment]
Closing as the issue has been resolved in the latest release
