### ISSUE TITLE
Error when trying to interact with an account via the extension

### ISSUE THREAD

**Issue by zmanian** [chainapsis/keplr-extension#60]
When I try to make transactions on `cosmoshub-4` with `cosmos1lcsjy2d5s33h0sddd8lpuqvwyz5ruz7jsfj43h`, I get `read property 'length' of undefined` on trying to send or withdraw rewards.

**Comment by Thunnini** [comment]
What webpage did this error occur in? and if it's a custom website, could you share some code snippets?

**Comment by zmanian** [comment]
this error occurs when I'm trying trying to use the extension directly and not via a website.

**Comment by dogemos** [comment]
It appears that the account is a vesting account, which Keplr may have issues supported after the Stargate upgrade. Just to verify, could you see if a non-vesting account has the same issue?

We're nearly complete with the refactor of Keplr, and once this has been released we'll make sure vesting accounts are supported for the latest version of the SDK as well.

**Comment by zmanian** [comment]
yeah that is probably why

**Comment by jbibla** [comment]
yep, can confirm the error is related to vesting accounts.

@dogemos do you have a rough timeline for the refactor + release?

**Comment by zmanian** [comment]
Just observe that I see the same vesting account errors on LedgerLive so it would be cool to have an example patch and we can fix both.

**Comment by jbibla** [comment]
@dogemos @Thunnini any ETA?

**Comment by dogemos** [comment]
We've just released v0.8.0 which should have resolved this issue. Could you guys check and see if everything works alright now?

**Comment by zmanian** [comment]
It works!
