### ISSUE TITLE
Error not enough gas 

### ISSUE THREAD

**Issue by wizard1786** [chainapsis/keplr-extension#69]
I have staked/delegated ATOM before without problems. Added aprox 12 and when I try to delegate it says not enough "gas". Please help thanks
![Satom 1](https://user-images.githubusercontent.com/36571950/110657294-b8c21b80-818e-11eb-9cc4-36dd89a5fe60.jpg)
![atom](https://user-images.githubusercontent.com/36571950/110657296-b95ab200-818e-11eb-9679-395e3f65809b.jpg)
![Satom 1](https://user-images.githubusercontent.com/36571950/110657362-c5df0a80-818e-11eb-9d9f-db2aaaafc1d3.jpg)

**Comment by dogemos** [comment]
This is because `Available Balance < Delegate Amount + Tx Fee`

Try delegating 12.3 ATOM and leave 0.1 ATOM to pay for tx fees.

**Comment by wizard1786** [comment]
Did not work Thanks for trying

**Comment by ungut72** [comment]
<img width="363" alt="Снимок экрана 2024-02-03 в 10 58 05" src="https://github.com/chainapsis/keplr-wallet/assets/158675882/4d95c7a9-a90e-4065-a88d-298ceabd939e">
Подскажите где взять этот газ? не могу вывести с кошелька KAVA на балансе есть свободный Cosmos
