### ISSUE TITLE
Keplr Wallet Is Not Showing All My Crypto

### ISSUE THREAD

**Issue by cage17wlc** [chainapsis/keplr-extension#72]
On, 2/25/21, I sent 135.999 ATOM to the keplr wallet from Trust Wallet. I have a successful confirmation for this transaction in Trust Wallet and on MINTSCAN. Keplr is only showing 48.70021 ATOM in my available balance. I need someone to correct this issue. The last person that looked into this issue did not resolve it.

**Comment by cage17wlc** [comment]
I urgently need this issue to be resolved. It has been over 22 days with no resolution to a large amount of money and crypto MISSING because of issues with Keplr Wallet!

**Comment by cage17wlc** [comment]
Is there anyone who can provide help or support for the Keplr Wallet issue mentioned above? @dogemos

**Comment by dogemos** [comment]
Please email your address and the tx hash of the transfer to hello@chainapsis.com. Happy to assist you over email/TG, but would prefer to keep your personal info outside of a public repository.

**Comment by cage17wlc** [comment]
@dogemos Thank you - I sent the email to the address you mentioned above.

**Comment by dogemos** [comment]
Closing the issue as the issue has been addressed via email.
