### ISSUE TITLE
Fail to withdraw rewards: Network Error

### ISSUE THREAD

**Issue by adamsmithsouza** [chainapsis/keplr-extension#73]
Try to claim my ATOM and AKASH rewards, the Keplr wallet returns the message: "Fail to withdraw rewards: Network Error".

It doesn't matter what tax i choose. Always the error appears.

Any suggestions? Tks!

**Comment by dogemos** [comment]
Hi @adamsmithsouza,

This is a known issue have been happening occasionally on Akash network, but we are still trying to actively identify the issue as we've never been able to replicate the error on our side.

To help us identify the issue, could you do the following:
• Go to chrome://extensions/
• Find Chrome, and click on ‘inspect views background page’
• Open the ‘Networks’ tab
• Try the action that doesn’t work (for example, stake/claim reward/send/etc)
• Click on the ‘txs’ that shows up (Photo 1)
• Send screen shot of the ‘Headers’,‘Preview’, and the ‘Response’ tab (Photo 2)

Please feel free to email the responses to keplr@chainapsis.com.

In the meantime, please try a different browser (Brave if you were using Chrome, Chrome if you were using Brave) or try to import the account on a different computer for now and see if that resolves the issue.
