### ISSUE TITLE
Support to sign arbitrary message

### ISSUE THREAD

**Issue by Tore19** [chainapsis/keplr-extension#74]
Seems Keplr does not support signing arbitrary messages. For now, we have to call signDirect and input a signDoc struct.
Any idea to support to sign arbitrary message?

**Comment by Tore19** [comment]
Hi, what I talked is not about cosmos chain transactions, just about public and private keys and signature algorithms. In our business, we want the user to sign something(arbitrary binary data) using user's private key through Keplr and then we can verify the signature using user's pubkey.

Any response for this?

**Comment by iicc1** [comment]
Hello, any update on this? Is there any way to sign a message with Keplr like Metamask?

**Comment by dogemos** [comment]
Closing and linking the latest issue: https://github.com/chainapsis/keplr-extension/issues/207
