### ISSUE TITLE
bug: clearDecimals ends up displaying wrong amount in confirmation message

### ISSUE THREAD

**Issue by clockworkgr** [chainapsis/keplr-extension#76]
here: https://github.com/chainapsis/keplr-extension/blob/develop/packages/extension/src/pages/sign/messages.tsx#L614

It works fine if the amount is in fact a decimal (e.g. 200.2500 which returns 200.25)
but not if it isn't.
E.g. 
`clearDecimals("200")`

returns 2

**Comment by Thunnini** [comment]
Thank you for your reporting!
