### ISSUE TITLE
sing tx

### ISSUE THREAD

**Issue by dimakorzhovnik** [chainapsis/keplr-extension#78]
sometimes I have a mistake in work keplr. when I'm creating tx and broadcast with signAndBroadcast, window sing in keplr is white, but if I do the transaction again and everything is fine 
the same error in keplr dashboard

and keplr don't work with os windows 

![Снимок экрана 2021-03-20 в 19 25 20](https://user-images.githubusercontent.com/36644677/113474332-112bc680-9478-11eb-91ee-a6b20a9bbc47.png)

<img width="969" alt="Снимок экрана 2021-03-20 в 19 24 56" src="https://user-images.githubusercontent.com/36644677/113474318-01ac7d80-9478-11eb-906d-ad6bd9cdc42e.png">

![Снимок экрана 2021-03-20 в 19 25 07](https://user-images.githubusercontent.com/36644677/113474327-0c671280-9478-11eb-8339-cc345d352f4c.png)

![2021-04-03 12 29 05](https://user-images.githubusercontent.com/36644677/113474353-36b8d000-9478-11eb-88d4-a08c51b540f4.jpg)

**Comment by dimakorzhovnik** [comment]
#89

**Comment by Thunnini** [comment]
Confirmed. Will be releasing a fix for it soon.
