### ISSUE TITLE
how export the private key of single account?

### ISSUE THREAD

**Issue by DanubioBlu** [chainapsis/keplr-extension#79]
I want export the private key of the secret network.
I have already backup the seed but I want export also the pk 

is it possible? 
thanks

**Comment by dogemos** [comment]
Right now we only support private key exports for Torus/Google Logins, as most other Cosmos wallets do not support importing the account from a private key and only support mnemonic seeds.

Feel free to check out open-sourced tools such as [this](https://github.com/toschdev/cosmos-bip44) to derive various private keys based on the mnemonics, though.
