### ISSUE TITLE
Content is not displayed in sifchain.

### ISSUE THREAD

**Issue by creamjun** [chainapsis/keplr-extension#81]
When the sifchain network is selected, the contents of the wallet are not displayed and only white panel without any content.

**Comment by creamjun** [comment]
The issue was recorded.
https://drive.google.com/file/d/1tYIyxi7bra8HoanWv74-gqG_PupKRh0f/view?usp=sharing

**Comment by dogemos** [comment]
Hi @creamjun,

Sorry to hear that you've been having issues with the extension. To help us better track down the issue, could you provide some of the following information to help us better track down what may be going wrong:
* Chrome version
* Keplr extension version
* Screenshot of the **extension's** console (right click within the extension -> click 'inspect' -> select the 'console' tab)

**Comment by creamjun** [comment]
Chrome :  90.0.4430.72
Kepler extension : 0.8.5

![image](https://user-images.githubusercontent.com/3322405/114916970-64cae680-9e60-11eb-9f1a-9401d80f4ba3.png)

**Comment by litvintech** [comment]
Maybe in some version of Сhrome webassembly's features are disabled by default and this cause problem?

**Comment by creamjun** [comment]
Resolved in v0.8.6.
