### ISSUE TITLE
Sifchain non-native "cTokens" List Does Not Display in Wallet

### ISSUE THREAD

**Issue by 59023g** [chainapsis/keplr-extension#83]
This issue relates to the Token List. Prior to this upgrade all our "cTokens" (cUSDT, cETH, etc) were listed in the Keplr wallet. This allowed users to see their balances and transact with these non-native "cTokens".

Here you can see I have "cToken" balances in cUSDT and cETH, however they are not in my Keplr wallet

<img width="866" alt="Screen Shot 2021-04-16 at 9 13 15 AM" src="https://user-images.githubusercontent.com/5235538/115037773-6f06d800-9e94-11eb-994f-04e231297086.png">
<img width="811" alt="Screen Shot 2021-04-16 at 9 13 24 AM" src="https://user-images.githubusercontent.com/5235538/115037788-7332f580-9e94-11eb-9a0c-83a2eaac8bff.png">

On our development network, you can see the expected behavior that existed prior to this update:

<img width="841" alt="Screen Shot 2021-04-16 at 9 18 37 AM" src="https://user-images.githubusercontent.com/5235538/115038141-db81d700-9e94-11eb-82ce-44de26113334.png">
<img width="371" alt="Screen Shot 2021-04-16 at 9 18 20 AM" src="https://user-images.githubusercontent.com/5235538/115038186-e63c6c00-9e94-11eb-9325-ef10567981cb.png">

**Comment by Thunnini** [comment]
This should be resolved in v0.8.6

**Comment by 59023g** [comment]
Tested, fixed. Thanks
