### ISSUE TITLE
Wallet won't let me stake AKT.

### ISSUE THREAD

**Issue by adiantum61** [chainapsis/keplr-extension#87]
I keep getting network error signal when trying to stake AKT.  Have tried different validators and gas prices.

**Comment by MbBrainz** [comment]
Which browser are you using and what version? A friend of mine experienced claiming and staking errors when using microsoft edge. If you're not yet using chrome I recommend you give it a try and see if the errors continue to show up.

**Comment by adiantum61** [comment]
Been using Chrome since I started interacting with Akash and Keplr.  Just updated it this morning and got the network error again when I tried to stake.

**Comment by adiantum61** [comment]
Now I've given up trying to stake it, and the wallet won't even let me send the AKT back to the exchange I got it from to trade it out!  Again I get "network error"!!  So now I have over $100 of it just stuck there!!
