### ISSUE TITLE
Update api endpoints for cyber.

### ISSUE THREAD

**Issue by mrlp4** [chainapsis/keplr-extension#90]
We migrated to new api-endpoints for euler-6 chain.
would really appreciate updating them in Keplr as well.
https://rpc.euler-6.cybernode.ai
https://lcd.euler-6.cybernode.ai

**Comment by dogemos** [comment]
Marking as resolved.

**Comment by mrlp4** [comment]
@dogemos  in which version it would be\was  implemented?
