### ISSUE TITLE
Creating a new contact prefills the address from previously created contact

### ISSUE THREAD

**Issue by fedekunze** [chainapsis/keplr-extension#91]
When adding two contacts to the Keplr address book, the second contact will have the address field prefilled with the first contact address.

Steps to reproduce:

1. Add contact to address book
2. `Add New` contact
3. Address will have the address prefilled

**Comment by dogemos** [comment]
Thanks for the report @fedekunze.

Confirmed that I was able to reproduce the error, and we'll be releasing a fix on our next release.
