### ISSUE TITLE
Failing to sign TX's when account number is 0

### ISSUE THREAD

**Issue by alimoabd2127** [chainapsis/keplr-extension#96]
If a user launches a Starport network to production, the account number used by the genesis accounts are 0.  Should you try to import the account into Keplr, it will successfully sign in and retrieve the balance. But when you attempt to send tokens, it will fail.  

This issue can also be replicated by creating a new account through Keplr, deleting it, and reimporting.  Initially you can send tokens, but once you reimport, the TX signing issue will return.

Keplr will succeed for this URL:
http://api.nekochain.com:1317/auth/accounts/neko17565uptp6ne6mn9q5c0tyvd62ydc70mgnc6x7r

But it will fail for the following one:
http://api.nekochain.com:1317/auth/accounts/neko1gpayvdn2tlspek257peusuy0t3jnn06w9hfcmk

Here's the network error when attempting to send through Keplr.
```
{
  "height":0,
  "code":4,
  "transactionHash":"281ECF474442ED4F1564FE12365CF32D16681738C5EB168549104FAF898A27D4",
  "rawLog":"signature verification failed; please verify account number (0) and chain-id (neko-3): unauthorized"
}
```

**Comment by V-Staykov** [comment]
I am experiencing the same problem and traced back the issue to this:
https://github.com/cosmos/cosmos-sdk/pull/6949

**Comment by Thunnini** [comment]
I'm really sorry for the very slow reply. Will be fixed in next version

**Comment by akcgjc007** [comment]
This issue still exists. Any updates?
![image](https://user-images.githubusercontent.com/56300182/170695649-6af533af-d852-43dd-921c-c8aeb965c5d5.png)

**Comment by alpha-omega-labs** [comment]
Confirming same issue: https://github.com/chainapsis/keplr-wallet/issues/419

**Comment by schnetzlerjoe** [comment]
> This issue still exists. Any updates? ![image](https://user-images.githubusercontent.com/56300182/170695649-6af533af-d852-43dd-921c-c8aeb965c5d5.png)

Same issue
